#### Numpy: Numerical Python

In [5]:
sales = [1,2,5,8,4,7]
sales

[1, 2, 5, 8, 4, 7]

In [6]:
import numpy as np

1. Creating Numpy Array

In [ ]:
sales_array = np.array(sales)
sales_array

array([1, 2, 5, 8, 4, 7])

2. Checking type.

In [8]:
type(sales_array)

numpy.ndarray

### Array Properties

In [10]:
sales_array.ndim # return dimension of the array that either the array is 1D, 2D or some other dimension.

1

In [12]:
sales_array.shape  # shows structure of Array.

(6,)

### Array Creation

In [15]:
# np.ones((rows, columns), dtype)
# np.ones create array containing only 1 as element in the entire array.

array_ones = np.ones((3,2), dtype=int)
array_ones


array([[1, 1],
       [1, 1],
       [1, 1]])

In [16]:
array_ones.ndim

2

In [17]:
array_ones.shape

(3, 2)

In [18]:
# np.zeros((rows, columns), dtype)
zeros_array = np.zeros((2,4))
zeros_array


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# np.arrange(start, stop, step_size)
custom_array = np.arange(1,11,3)
custom_array

array([ 1,  4,  7, 10])